# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'JFrog Artifactory V2'
    sourceRepo: 'amitl-npm'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JfrogCliV2@1
  inputs:
    command: 'jf npm publish --build-name $(Build.DefinitionName) --build-number $(Build.BuildNumber)'
             
    workingDirectory: '/npm-exapmle'
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'amitlAzureDev'
    command: 'jf rt bp $(Build.DefinitionName) $(Build.BuildNumber)'
    workingDirectory: '/npm-example'